### ISSUE TITLE
Allow user to change themes

### ISSUE THREAD

**Issue by faraazahmad** [faraazahmad/markr#1]
Create a themes dialog with a limited set (at least 4) of themes as per the [material design pallete](http://www.materialpalette.com/), to enable the user to change themes as per choice.

**Comment by faraazahmad** [comment]
You can find the material web component for dialogs [here](https://material.io/components/web/catalog/dialogs/)

**Comment by daubaris** [comment]
Can I take this issue?

**Comment by faraazahmad** [comment]
Sure!

**Comment by daubaris** [comment]
Cool, I'll update you on the progress.

**Comment by Barathwaja** [comment]
Any plans in adding more cool CSS?? @faraazahmad !!

**Comment by Barathwaja** [comment]
Any plans of changing UI for markr website (CSS)?? @faraazahmad

**Comment by faraazahmad** [comment]
the website in the readme is not of markr but a repo markr is based on. I'll update the link in a while

**Comment by luantranminh** [comment]
I can figure it out. As my repo markr, I allow user change theme, randomly.

**Comment by faraazahmad** [comment]
We want the user to change the theme as they want, not randomly

**Comment by faraazahmad** [comment]
@daubaris any update?
